### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by ri0t** [FayDoom/Strobe#2]
Nice project!
Here are some further improvement suggestions:
* [ ] Switch from argparser to the [wonderful click library](https://click.palletsprojects.com/en/7.x/)
* [x] Write a generic connector class to remove redundant code (I've already begun that)
* [ ] Write a [test suite with pytest](https://docs.pytest.org/en/latest/) ;D
* [x] Add a license (I much :heart: GPLv3)
* [ ] Add docstrings
* [ ] Reduce size by permanently removing __pycache__ from git history

**Comment by FayDoom** [comment]
Perfect !
Right now, I'm working on a connecter pulling data from the satellite Terra's Modis instrument. :)
I don't think we can create an unified connecter since the data's sources are différents.

I'm quite curious about how you want to do that.
